[settings]
pin = true

[tools]
go = "1.24.2"

[tasks.local]
run = "go run main.go"

[tasks.check]
description = "Run all static analysis tools"
depends = ['staticcheck','vulncheck','deadcode','vet']

[tasks.staticcheck]
description = "Run staticcheck"
wait_for = ['fmt']
run = "go tool honnef.co/go/tools/cmd/staticcheck ./..."

[tasks.vulncheck]
description = "Run govulncheck"
wait_for = ['fmt']
run = "go tool golang.org/x/vuln/cmd/govulncheck ./..."

[tasks.deadcode]
description = "Run deadcode"
wait_for = ['fmt']
run = "go tool golang.org/x/tools/cmd/deadcode -test ./..."

[tasks.gosec]
description = "Run gosec"
wait_for = ['fmt']
run = "go tool github.com/securego/gosec/v2/cmd/gosec --exclude-generated -terse ./..."

[tasks.vet]
description = "Run go vet"
wait_for = ['fmt']
run = "go vet ./..."

[tasks.test]
wait_for = ['fmt']
description = "Run tests"
run = "go test ./... -v"

[tasks.fmt]
description = "Format all go code using gofumpt"
run = "go tool mvdan.cc/gofumpt -w ./"
